# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "791f0e641f13f84c583b0ab951dd7f1d"
name = "checkout-extension"
handle = "checkout-extension-620"
application_url = "https://easily-round-detected-hungary.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e991aa24.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://easily-round-detected-hungary.trycloudflare.com/auth/callback",
  "https://easily-round-detected-hungary.trycloudflare.com/auth/shopify/callback",
  "https://easily-round-detected-hungary.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "pubsub://divine-booking-438923-u1:shopify-orders"

[pos]
embedded = false
